# Generated by Django 4.2.9 on 2024-04-10 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Quizzes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quiz",
            name="imagen",
            field=models.ImageField(
                default="imagen", upload_to="core/assets/images/quizzes/"
            ),
        ),
    ]
